# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'data.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FormData(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(690, 618)
        self.tableWidget = QtWidgets.QTableWidget(Form)
        self.tableWidget.setGeometry(QtCore.QRect(30, 110, 631, 461))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(6)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(40, 20, 171, 61))
        self.label.setStyleSheet("font: 24pt \"Times New Roman\";")
        self.label.setObjectName("label")
        self.add = QtWidgets.QPushButton(Form)
        self.add.setGeometry(QtCore.QRect(210, 40, 75, 23))
        self.add.setObjectName("add")
        self.id = QtWidgets.QLineEdit(Form)
        self.id.setGeometry(QtCore.QRect(300, 40, 31, 20))
        self.id.setObjectName("id")
        self.dell = QtWidgets.QPushButton(Form)
        self.dell.setGeometry(QtCore.QRect(330, 40, 75, 20))
        self.dell.setObjectName("dell")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Form", "ID"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Form", "FK_MemberID"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Form", "FK_ProductID"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Form", "CurrentDate"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("Form", "Purchase_price"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("Form", "Selling_price"))
        self.label.setText(_translate("Form", "Actual Data"))
        self.add.setText(_translate("Form", "Добавить"))
        self.id.setPlaceholderText(_translate("Form", "id"))
        self.dell.setText(_translate("Form", "Удалить"))
