# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'newData.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FormNewData(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(372, 333)
        self.verticalLayoutWidget = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(50, 30, 281, 271))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(15)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label.setStyleSheet("font: 24pt \"Times New Roman\";")
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.FK_MemberID = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.FK_MemberID.setObjectName("FK_MemberID")
        self.verticalLayout.addWidget(self.FK_MemberID)
        self.FK_ProductID = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.FK_ProductID.setObjectName("FK_ProductID")
        self.verticalLayout.addWidget(self.FK_ProductID)
        self.CurrentDate = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.CurrentDate.setObjectName("CurrentDate")
        self.verticalLayout.addWidget(self.CurrentDate)
        self.Purchase_price = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.Purchase_price.setObjectName("Purchase_price")
        self.verticalLayout.addWidget(self.Purchase_price)
        self.Selling_price = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.Selling_price.setObjectName("Selling_price")
        self.verticalLayout.addWidget(self.Selling_price)
        self.add = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.add.setObjectName("add")
        self.verticalLayout.addWidget(self.add)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "New Actual Data"))
        self.FK_MemberID.setPlaceholderText(_translate("Form", "FK_MemberID"))
        self.FK_ProductID.setPlaceholderText(_translate("Form", "FK_ProductID "))
        self.CurrentDate.setPlaceholderText(_translate("Form", "CurrentDate"))
        self.Purchase_price.setPlaceholderText(_translate("Form", "Purchase_price"))
        self.Selling_price.setPlaceholderText(_translate("Form", "Selling_price"))
        self.add.setText(_translate("Form", "Записать"))
