# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'newMember.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FormNewMember(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(372, 333)
        self.verticalLayoutWidget = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(50, 30, 281, 271))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(15)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label.setStyleSheet("font: 24pt \"Times New Roman\";")
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.Second_name = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.Second_name.setObjectName("Second_name")
        self.verticalLayout.addWidget(self.Second_name)
        self.First_name = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.First_name.setObjectName("First_name")
        self.verticalLayout.addWidget(self.First_name)
        self.Surname = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.Surname.setObjectName("Surname")
        self.verticalLayout.addWidget(self.Surname)
        self.Post = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.Post.setObjectName("Post")
        self.verticalLayout.addWidget(self.Post)
        self.FK_PlantID = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.FK_PlantID.setObjectName("FK_PlantID")
        self.verticalLayout.addWidget(self.FK_PlantID)
        self.add = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.add.setObjectName("add")
        self.verticalLayout.addWidget(self.add)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "New Member"))
        self.Second_name.setPlaceholderText(_translate("Form", "Second_name"))
        self.First_name.setPlaceholderText(_translate("Form", "First_name "))
        self.Surname.setPlaceholderText(_translate("Form", "Surname"))
        self.Post.setPlaceholderText(_translate("Form", "Post"))
        self.FK_PlantID.setPlaceholderText(_translate("Form", "FK_PlantID"))
        self.add.setText(_translate("Form", "Записать"))
