# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'newProduct.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FormNewProduct(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(372, 274)
        self.verticalLayoutWidget = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(50, 20, 281, 221))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(15)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label.setStyleSheet("font: 24pt \"Times New Roman\";")
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.IndexProduct = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.IndexProduct.setObjectName("IndexProduct")
        self.verticalLayout.addWidget(self.IndexProduct)
        self.NameProduct = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.NameProduct.setObjectName("NameProduct")
        self.verticalLayout.addWidget(self.NameProduct)
        self.Sort = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.Sort.setObjectName("Sort")
        self.verticalLayout.addWidget(self.Sort)
        self.GroupProduct = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.GroupProduct.setObjectName("GroupProduct")
        self.verticalLayout.addWidget(self.GroupProduct)
        self.add = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.add.setObjectName("add")
        self.verticalLayout.addWidget(self.add)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "New Product"))
        self.IndexProduct.setPlaceholderText(_translate("Form", "IndexProduct"))
        self.NameProduct.setPlaceholderText(_translate("Form", "NameProduct"))
        self.Sort.setPlaceholderText(_translate("Form", "Sort"))
        self.GroupProduct.setPlaceholderText(_translate("Form", "GroupProduct"))
        self.add.setText(_translate("Form", "Записать"))
