# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'newPlant.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FormNewPlant(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(372, 369)
        self.verticalLayoutWidget = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(50, 20, 281, 321))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(15)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label.setStyleSheet("font: 24pt \"Times New Roman\";")
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.IndexPlant = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.IndexPlant.setObjectName("IndexPlant")
        self.verticalLayout.addWidget(self.IndexPlant)
        self.NamePlant = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.NamePlant.setObjectName("NamePlant")
        self.verticalLayout.addWidget(self.NamePlant)
        self.Region = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.Region.setObjectName("Region")
        self.verticalLayout.addWidget(self.Region)
        self.City = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.City.setObjectName("City")
        self.verticalLayout.addWidget(self.City)
        self.Street = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.Street.setObjectName("Street")
        self.verticalLayout.addWidget(self.Street)
        self.Building = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.Building.setObjectName("Building")
        self.verticalLayout.addWidget(self.Building)
        self.Phone = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.Phone.setObjectName("Phone")
        self.verticalLayout.addWidget(self.Phone)
        self.add = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.add.setObjectName("add")
        self.verticalLayout.addWidget(self.add)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "New Plant"))
        self.IndexPlant.setPlaceholderText(_translate("Form", "IndexPlant"))
        self.NamePlant.setPlaceholderText(_translate("Form", "NamePlant "))
        self.Region.setPlaceholderText(_translate("Form", "Region"))
        self.City.setPlaceholderText(_translate("Form", "City"))
        self.Street.setPlaceholderText(_translate("Form", "Street"))
        self.Building.setPlaceholderText(_translate("Form", "Building"))
        self.Phone.setPlaceholderText(_translate("Form", "Phone"))
        self.add.setText(_translate("Form", "Записать"))
