# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'signin.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(300, 339)
        self.verticalLayoutWidget = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 300, 339))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.container = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.container.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.container.setContentsMargins(20, 20, 20, 20)
        self.container.setSpacing(20)
        self.container.setObjectName("container")
        self.login = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.login.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.login.setFont(font)
        self.login.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.login.setObjectName("login")
        self.container.addWidget(self.login)
        self.username = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.username.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.username.sizePolicy().hasHeightForWidth())
        self.username.setSizePolicy(sizePolicy)
        self.username.setMinimumSize(QtCore.QSize(0, 0))
        self.username.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.username.setFont(font)
        self.username.setCursor(QtGui.QCursor(QtCore.Qt.WaitCursor))
        self.username.setStyleSheet("")
        self.username.setFrame(False)
        self.username.setObjectName("username")
        self.container.addWidget(self.username)
        self.password = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.password.setFont(font)
        self.password.setFrame(False)
        self.password.setObjectName("password")
        self.container.addWidget(self.password)
        self.signin = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.signin.setFont(font)
        self.signin.setStyleSheet("")
        self.signin.setObjectName("signin")
        self.container.addWidget(self.signin)
        self.order = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.order.setFont(font)
        self.order.setObjectName("order")
        self.container.addWidget(self.order)
        self.password.raise_()
        self.username.raise_()
        self.order.raise_()
        self.login.raise_()
        self.signin.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.login.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt;\">Авторизация</span></p></body></html>"))
        self.username.setPlaceholderText(_translate("Form", "username"))
        self.password.setPlaceholderText(_translate("Form", "password"))
        self.signin.setText(_translate("Form", "Вход"))
        self.order.setText(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Для входа незарегистрированному пользователю </p>\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">ввести [имя-user, пароль-оставить пустым] </p></body></html>"))
